# version: '3.8'
services:
  db:
    image: postgres:15.1
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    env_file:
      - .dev.env
  pgadmin:
    image: dpage/pgadmin4:6.18
    ports:
      - "8080:80"
    volumes:
      - pgadmindata:/var/lib/pgadmin
    env_file:
      - .dev.env
    depends_on:
      - db
#  api:
#    build: .
#    image: nest-api-dev
#    volumes:
#      - /Users/vladislavminchuk/work/back-game-app/src/:/app/src
#    env_file:
#    - .dev.env
#    ports:
#      - 3000:3000
#    depends_on:
#      - db

volumes:
  pgadmindata: {}
  dbdata: {}